# Generated by Django 5.2.2 on 2025-06-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameProgress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementdefinition',
            name='unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
