# Generated by Django 5.2.2 on 2025-06-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameProgress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementdefinition',
            name='unlocked',
        ),
    ]
