# Generated by Django 5.2.5 on 2025-09-22 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GameProgress', '0001_initial'),
        ('StudentManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.student'),
        ),
        migrations.AddField(
            model_name='levelprogress',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameProgress.leveldefinition'),
        ),
        migrations.AddField(
            model_name='levelprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.student'),
        ),
        migrations.AddField(
            model_name='sectionlevelschedule',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameProgress.leveldefinition'),
        ),
        migrations.AddField(
            model_name='sectionlevelschedule',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.section'),
        ),
        migrations.AddIndex(
            model_name='achievementprogress',
            index=models.Index(fields=['student'], name='GameProgres_student_295b76_idx'),
        ),
        migrations.AddIndex(
            model_name='achievementprogress',
            index=models.Index(fields=['unlocked'], name='GameProgres_unlocke_32c567_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='achievementprogress',
            unique_together={('student', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='levelprogress',
            index=models.Index(fields=['student'], name='GameProgres_student_6cead3_idx'),
        ),
        migrations.AddIndex(
            model_name='levelprogress',
            index=models.Index(fields=['best_time'], name='GameProgres_best_ti_6187ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='levelprogress',
            unique_together={('student', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='sectionlevelschedule',
            unique_together={('section', 'level')},
        ),
    ]
