# Generated by Django 5.2.2 on 2025-06-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameProgress', '0002_remove_achievementdefinition_unlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementdefinition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
