# Generated by Django 5.2.5 on 2025-09-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameProgress', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementprogress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='levelprogress',
            name='unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
