# Generated by Django 5.2.5 on 2025-09-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameProgress', '0003_achievementprogress_is_active_levelprogress_unlocked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievementdefinition',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='leveldefinition',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='leveldefinition',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
