# Generated by Django 5.2.5 on 2025-09-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameProgress', '0004_alter_achievementdefinition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveldefinition',
            name='sort_order',
            field=models.IntegerField(default=999),
        ),
    ]
