# Generated by Django 5.2.5 on 2025-09-18 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameProgress', '0005_alter_leveldefinition_sort_order'),
        ('StudentManagementSystem', '0007_student_login_key_teacher_login_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionLevelSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameProgress.leveldefinition')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.section')),
            ],
            options={
                'unique_together': {('section', 'level')},
            },
        ),
    ]
