# Generated by Django 5.2.5 on 2025-09-09 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ADMIN', 'Admin')], default='ADMIN', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='StudentMana_name_0df7c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.department')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ADMIN', 'Admin')], default='TEACHER', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['teacher_id'], name='StudentMana_teacher_620fa4_idx'), models.Index(fields=['last_name', 'first_name'], name='StudentMana_last_na_b6a36f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('middle_initial', models.CharField(blank=True, max_length=5, null=True)),
                ('suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=150, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_backgrounds', to='StudentManagementSystem.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['year'], name='StudentMana_year_c2b100_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ADMIN', 'Admin')], default='STUDENT', max_length=20)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.section')),
                ('year_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.yearlevel')),
            ],
        ),
        migrations.CreateModel(
            name='SectionJoinCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.department')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.section')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.yearlevel')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.yearlevel'),
        ),
        migrations.CreateModel(
            name='HandledSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.department')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handled_sections', to='StudentManagementSystem.teacher')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.yearlevel')),
            ],
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['content_type', 'object_id'], name='StudentMana_content_a6ebe3_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='StudentMana_student_4ba16d_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_name', 'first_name'], name='StudentMana_last_na_ab2842_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['year_level', 'section'], name='StudentMana_year_le_50e5dd_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionjoincode',
            index=models.Index(fields=['section', 'department', 'year_level'], name='StudentMana_section_d87578_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sectionjoincode',
            unique_together={('section', 'department', 'year_level')},
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['department', 'year_level', 'letter'], name='StudentMana_departm_4dc12c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('department', 'year_level', 'letter')},
        ),
        migrations.AddIndex(
            model_name='handledsection',
            index=models.Index(fields=['teacher', 'department', 'year_level', 'section'], name='StudentMana_teacher_742eb3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='handledsection',
            unique_together={('teacher', 'department', 'year_level', 'section')},
        ),
    ]
