# Generated by Django 5.2.5 on 2025-08-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='StudentMana_name_0df7c8_idx'),
        ),
        migrations.AddIndex(
            model_name='handledsection',
            index=models.Index(fields=['teacher', 'department', 'year_level', 'section'], name='StudentMana_teacher_742eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['department', 'year_level', 'letter'], name='StudentMana_departm_4dc12c_idx'),
        ),
        migrations.AddIndex(
            model_name='sectionjoincode',
            index=models.Index(fields=['section', 'department', 'year_level'], name='StudentMana_section_d87578_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='StudentMana_student_4ba16d_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_name', 'first_name'], name='StudentMana_last_na_ab2842_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['year_level', 'section'], name='StudentMana_year_le_50e5dd_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['teacher_id'], name='StudentMana_teacher_620fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['last_name', 'first_name'], name='StudentMana_last_na_b6a36f_idx'),
        ),
        migrations.AddIndex(
            model_name='yearlevel',
            index=models.Index(fields=['year'], name='StudentMana_year_c2b100_idx'),
        ),
    ]
