# Generated by Django 5.2.5 on 2025-09-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
