# Generated by Django 5.2.2 on 2025-06-08 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.department'),
        ),
        migrations.AlterField(
            model_name='section',
            name='year_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.yearlevel'),
        ),
    ]
