# Generated by Django 5.2.5 on 2025-10-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('StudentManagementSystem', '0002_userprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
