# Generated by Django 5.2.2 on 2025-06-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0002_alter_section_department_alter_section_year_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='department',
        ),
        migrations.RemoveField(
            model_name='section',
            name='year_level',
        ),
    ]
