# Generated by Django 5.2.2 on 2025-06-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0003_remove_section_department_remove_section_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='StudentManagementSystem.department'),
        ),
    ]
