# Generated by Django 5.2.5 on 2025-09-11 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0003_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='actor_name',
        ),
    ]
