# Generated by Django 5.2.5 on 2025-09-11 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0004_remove_log_actor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='target_model',
        ),
    ]
