# Generated by Django 5.2.5 on 2025-09-11 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0005_remove_log_target_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='target_id',
        ),
    ]
