# Generated by Django 5.2.5 on 2025-09-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0006_remove_log_target_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login_key',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='login_key',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True, unique=True),
        ),
    ]
