# Generated by Django 5.2.5 on 2025-09-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0008_testdefinition_testquestion_testchoice_studenttest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testchoice',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='testchoice',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
