# Generated by Django 5.2.5 on 2025-09-21 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0009_alter_testchoice_options_testchoice_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.PositiveIntegerField(default=0)),
                ('page_size', models.PositiveIntegerField(default=25)),
                ('question_order', models.JSONField(default=list)),
                ('choice_orders', models.JSONField(default=dict)),
                ('answers', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.testdefinition')),
            ],
            options={
                'unique_together': {('student', 'test')},
            },
        ),
    ]
