# Generated by Django 5.2.5 on 2025-09-22 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0010_studentprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdefinition',
            name='description',
        ),
        migrations.CreateModel(
            name='TestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tests', to='StudentManagementSystem.section')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='StudentManagementSystem.testdefinition')),
            ],
            options={
                'unique_together': {('test', 'section')},
            },
        ),
    ]
